### ISSUE TITLE
Latest build at jitpack.io failed

### ISSUE THREAD

**Issue by yaleh** [ctodobom/OpenCV-3.1.0-Android#4]
Build starting...
Start: Thu Mar 16 23:01:17 UTC 2017
Git:
3.1.0
commit 92387b1ef8fad15196dd5f7fb4931444a68bc93a
Author: Maksim Shabunin 
Date:   Fri Dec 18 18:02:16 2015 +0300

    Fix java version++

ERROR:
No build file found. Looking for Gradle/Maven/Sbt/Lein build file in the root of the project
See the documentation at https://jitpack.io/docs/
Files: 
3rdparty
CMakeLists.txt
CONTRIBUTING.md
LICENSE
README.md
apps
cmake
data
doc
include
modules
platforms
samples
2017-03-16T23:01:17.627614724Z
Exit code: 1
No build artifacts found

**Comment by allgood** [comment]
@yaleh , I am not understanding your issue report. What is failing on jitpack.io? The files you listed looks like they are not from this repo. Packages from the last commit of this repo have been successfully build on jitpack.io: https://jitpack.io/#ctodobom/OpenCV-3.1.0-Android/9e00ee4218

**Comment by yaleh** [comment]
Sorry, my fault. It's a fork.
